repos:
  - repo: local
    hooks:
      - id: commit prefix
        name: commit prefix
        language: pygrep
        entry: '\A(?![A-Z]+-[0-9]+)'
        stages: [commit-msg]

      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]

